services:
  - type: web
    name: ai-chatbot-platform
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn -c gunicorn.conf.py wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: WEBHOOK_BASE_URL
        value: https://ai-chatbot-platform.onrender.com

databases:
  - name: chatbot-db
    plan: starter